from app.exceptions.admins import (
    AdminAlreadyExistsError,
    AdminUserNotFoundError,
    OwnAccessChangeError,
    OwnerNotEditableError,
    PermissionEscalationError,
    RoleInUseError,
    RoleNotFoundError,
    RoleTitleTakenError,
)
from app.exceptions.auth import (
    AdminAccessDeniedError,
    InvalidLoginCodeError,
    InvalidWidgetDataError,
    LoginUnavailableError,
    NotAuthenticatedError,
    PermissionDeniedError,
    TelegramUnavailableError,
    TooManyLoginAttemptsError,
    WidgetLoginDisabledError,
)
from app.exceptions.base import (
    AppError,
    AuthenticationError,
    AuthorizationError,
    ConflictError,
    ExternalServiceError,
    InvalidInputError,
    NotFoundError,
    TooManyRequestsError,
)
from app.exceptions.clubs import (
    BlockColumnTakenError,
    BlockHasMembersError,
    BlockNotFoundError,
    ClubNotFoundError,
    ClubTitleTakenError,
    InvalidBlockPeriodError,
)
from app.exceptions.common import EmptyUpdateError
from app.exceptions.settings import AppSettingsMissingError, VkLinkModeNotConfiguredError
from app.exceptions.sheet_syncs import ClubNotSyncableError, SheetSyncDisabledError
from app.exceptions.vk import (
    InvalidVkLinkError,
    UserNotRegisteredError,
    VkAccountTakenError,
    VkAlreadyLinkedError,
    VkLinkModeChangedError,
    VkLinkUnavailableError,
    VkProfileNotFoundError,
    VkUnavailableError,
)

__all__ = [
    "AdminAccessDeniedError",
    "AdminAlreadyExistsError",
    "AdminUserNotFoundError",
    "AppError",
    "AppSettingsMissingError",
    "AuthenticationError",
    "AuthorizationError",
    "BlockColumnTakenError",
    "BlockHasMembersError",
    "BlockNotFoundError",
    "ClubNotFoundError",
    "ClubNotSyncableError",
    "ClubTitleTakenError",
    "ConflictError",
    "EmptyUpdateError",
    "ExternalServiceError",
    "InvalidBlockPeriodError",
    "InvalidInputError",
    "InvalidLoginCodeError",
    "InvalidVkLinkError",
    "InvalidWidgetDataError",
    "LoginUnavailableError",
    "NotAuthenticatedError",
    "NotFoundError",
    "OwnAccessChangeError",
    "OwnerNotEditableError",
    "PermissionDeniedError",
    "PermissionEscalationError",
    "RoleInUseError",
    "RoleNotFoundError",
    "RoleTitleTakenError",
    "SheetSyncDisabledError",
    "TelegramUnavailableError",
    "TooManyLoginAttemptsError",
    "TooManyRequestsError",
    "UserNotRegisteredError",
    "VkAccountTakenError",
    "VkAlreadyLinkedError",
    "VkLinkModeChangedError",
    "VkLinkModeNotConfiguredError",
    "VkLinkUnavailableError",
    "VkProfileNotFoundError",
    "VkUnavailableError",
    "WidgetLoginDisabledError",
]
